TRAIN_RATIO: 0.6
VALIDATION_RATIO: 0.2
TEST_RATIO: 0.2
RESCALE: 1/255
IMG_HEIGHT: 200
IMG_WIDTH: 200
BATCH_SIZE: 100
CLASS_MODE: 'categorical'
EPOCHS: 5
CLASSES: 4
COLOR_MODE: 'grayscale'
LEARNING_RATE: 0.01